// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDVykImdbpD2CPR-MEofSESQDzXycHZT0',
    appId: '1:1011441431867:web:136322790e56af9436331e',
    messagingSenderId: '1011441431867',
    projectId: 'language-learning-app-29618',
    authDomain: 'language-learning-app-29618.firebaseapp.com',
    storageBucket: 'language-learning-app-29618.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJemcEuCcIZgQhbucWpUe73F5RU4SPqYM',
    appId: '1:1011441431867:android:4ab644908165e7dc36331e',
    messagingSenderId: '1011441431867',
    projectId: 'language-learning-app-29618',
    storageBucket: 'language-learning-app-29618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgAZnFZbQ8qmVGsQ8wb7OnKW68RiC1bnQ',
    appId: '1:1011441431867:ios:6a32e1d4e057dc3436331e',
    messagingSenderId: '1011441431867',
    projectId: 'language-learning-app-29618',
    storageBucket: 'language-learning-app-29618.appspot.com',
    iosBundleId: 'com.example.languageLearningAppFlutter',
  );
}
